# 一、ndarray
## 1.ndarray的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(1)
print(arr)
print("arr的维度：", arr.ndim)

1
arr的维度： 0


In [3]:
arr = np.array([1, 2, 3])
print(arr)
print("arr的维度：", arr.ndim)

[1 2 3]
arr的维度： 1


In [4]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print("arr的维度：", arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [5]:
arr = np.array([1, "hello"]) #强制转化
print(arr)


['1' 'hello']


In [6]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [7]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print("数组的形状",arr.shape) #2行3列

[[1 2 3]
 [4 5 6]]
数组的形状 (2, 3)


In [8]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print("数组的维度",arr.ndim)

[[1 2 3]
 [4 5 6]]
数组的维度 2


In [9]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print("元素的个数",arr.size)

[[1 2 3]
 [4 5 6]]
元素的个数 6


In [10]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print("数据类型",arr.dtype)

[[1 2 3]
 [4 5 6]]
数据类型 int64


In [11]:
arr = np.array([[1, 2.5, 3],[4, 5, 6]])
print(arr)
print("数据类型",arr.dtype)

[[1.  2.5 3. ]
 [4.  5.  6. ]]
数据类型 float64


In [12]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
print("元素的转置",arr.T)

[[1 2 3]
 [4 5 6]]
元素的转置 [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [13]:
list1 = [1, 2, 3] #基础
arr = np.array(list1)
print(arr)

[1 2 3]


In [18]:
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 9
print(arr1)
print(arr)

[1 2 3]
[9 2 3]
[1 2 3]


In [21]:
#预定义形状
#全0 全1 未初始化 固定值 类似
arr = np.zeros((3,3),dtype = np.int64)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
arr = np.ones((3,3),dtype = np.int64)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [24]:
arr = np.empty((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
arr = np.empty((10,2))
print(arr)

[[0.  0. ]
 [0.3 1. ]
 [0.  0. ]
 [1.  1. ]
 [1.  1. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]
 [0.  1. ]]


In [26]:
arr = np.full((4,2),2026)
print(arr)

[[2026 2026]
 [2026 2026]
 [2026 2026]
 [2026 2026]]


In [27]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [32]:
arr1 = np.empty_like(arr)
print(arr1)

[[0.  0. ]
 [0.3 1. ]
 [0.  0. ]
 [1.  1. ]
 [1.  1. ]
 [1.  1. ]
 [1.  0. ]
 [0.  1. ]
 [0.5 0. ]
 [0.  1. ]]


In [33]:
# 等差数列
arr = np.arange(1,10,2) # start,end(except),step
print(arr)

[1 3 5 7 9]


In [34]:
# 等间隔数列
arr = np.linspace(1,10,5) # start,end,份数(平均分配)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [35]:
# 对数间隔数列
arr = np.logspace(0,4,2,base=2)
print(arr)

[ 1. 16.]


In [36]:
arr = np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [37]:
arr = np.logspace(0,4,3,base=3)
print(arr)

[ 1.  9. 81.]


In [39]:
# 矩阵的构造
arr = np.eye(3) #三阶
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [48]:
# 随机数组的生成
arr = np.random.rand(2,3) # 0-1
print(arr)

[[0.04608686 0.45575161 0.11515799]
 [0.93622454 0.33685698 0.26535555]]


In [50]:
arr = np.random.uniform(3,6,(2,3)) # 范围，(形状)
print(arr)

[[4.87594134 4.01723089 3.79081876]
 [3.92677354 5.90173398 3.73093812]]


In [52]:
arr = np.random.randint(3,30,(2,3))
print(arr)

[[15 28 12]
 [ 7 20 25]]


In [60]:
# 正态分布
arr = np.random.randn(2,3)
print(arr)

[[-1.2177021  -0.45263739 -1.13349632]
 [ 0.52110514 -1.03326497 -0.57666105]]


In [66]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
