In [1]:
from ex5 import average

"""1.基础创建与属性：创建一个形状为 (3,4) 的二维数组，
   数组元素为 0 到 11 的连续整数，然后打印出该数组的形状、维度、元素总数和数据类型。"""
import numpy as np
arr0 = np.arange(0, 12)
arr = arr0.reshape((3, 4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
12
int64


In [2]:
"""2.数组索引与切片：基于第 1 题创建的数组，完成以下操作：
取出数组中第二行所有元素；
取出数组中第三列所有元素；
取出数组中第 1-2 行、第 2-3 列的子数组"""
import numpy as np
arr0 = np.arange(0, 12)
arr = arr0.reshape((3, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
a = arr[[1, 1, 1, 1],[0, 1, 2, 3]]
print(a)
b = arr[:,2]
print(b)

[4 5 6 7]
[ 2  6 10]


In [4]:
c = arr[0:2,1:3]
print(c)

[[1 2]
 [5 6]]


In [5]:
""""3.数组运算：创建两个形状为 (2,2) 的随机整数数组（取值范围 1-10），分别实现它们的逐元素加法、减法、乘法、矩阵乘法，并输出结果。"""
import numpy as np
arr1 = np.random.randint(1,11,size=(2,2))
arr2 = np.random.randint(1,11,size=(2,2))
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(np.dot(arr1,arr2))



[[4 8]
 [1 5]]
[[ 2  9]
 [ 2 10]]
[[ 6 17]
 [ 3 15]]
[[ 2 -1]
 [-1 -5]]
[[ 8 72]
 [ 2 50]]
[[ 24 116]
 [ 12  59]]


In [22]:
"""4.数组变形与拼接：
将第 1 题的 (3,4) 数组变形为 (4,3) 的数组；
创建一个形状为 (3,4)、元素全为 1 的数组，将其与第 1 题的数组按行拼接（最终形状为 (6,4)），再按列拼接（最终形状为 (3,8)）。"""
import  numpy as np
arr = np.arange(0, 12).reshape((4,3))
print(arr)
arr1 = np.ones((3,4))
print(arr1)
arr3 = np.arange(0, 12).reshape((3,4))
arr4 = np.vstack([arr1,arr3])
arr5 = np.hstack([arr1,arr3])
print(arr4)
print(arr5)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[ 1.  1.  1.  1.  0.  1.  2.  3.]
 [ 1.  1.  1.  1.  4.  5.  6.  7.]
 [ 1.  1.  1.  1.  8.  9. 10. 11.]]


In [35]:
"""5.统计与条件筛选：基于第 1 题的数组，完成以下操作：
计算数组的最大值、最小值、平均值、总和；
筛选出数组中大于 5 的所有元素，并输出这些元素的位置（索引）；
将数组中小于 3 的元素替换为 0，大于等于 3 的元素保持不变。"""
import  numpy as np
arr = np.arange(0, 12).reshape((3,4))
print(arr)
a = np.max(arr)
print(a)
b = np.min(arr)
print(b)
c = np.average(arr)
print(c)
d = np.sum(arr)
print(d)
e = arr > 5
print(e)
print(arr[e])
f = np.where(arr >= 5)
print(f)
g = arr < 3
print(g)
arr[g] = 0
print(arr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
0
5.5
66
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]
(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))
[[ True  True  True False]
 [False False False False]
 [False False False False]]
[[ 0  0  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [45]:
"""Addition"""
"""1.生成一个 4×4 的 0 矩阵，把对角线改成 1～4。"""
import numpy as np
arr = np.zeros((4,4), dtype=int)
print(arr)
arr[[0,1,2,3],[0,1,2,3]] = [1,2,3,4]
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [52]:
"""2.用 np.arange 生成 1～10，求平均值与总和。"""
import numpy as np
arr = np.arange(11, dtype=np.int32)
a = np.average(arr)
print(a)
b = sum(arr)
print(b)

5.0
55


In [53]:
"""3.创建两个 2×2 矩阵，分别做逐元素相乘和矩阵相乘"""
import numpy as np
arr1 = np.random.randint(1,11,size=(2,2))
arr2 = np.random.randint(1,11,size=(2,2))
print(arr1)
print(arr2)
a = arr1 * arr2
print(a)
b = np.dot(arr1, arr2)
print(b)

[[6 6]
 [5 2]]
[[4 3]
 [8 9]]
[[24 18]
 [40 18]]
[[72 72]
 [36 33]]
