In [2]:
"""1.生成 1~16 的数组，reshape 成 4×4，取出所有偶数。"""
import numpy as np
arr = np.arange(1,17).reshape(4,4)
print(arr)
a = arr % 2 == 0
print(a)
print(arr[a])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[ 2  4  6  8 10 12 14 16]


In [28]:
"""2.有一个 3×3 随机矩阵，求每一行的和、每一列的平均值。"""
import numpy as np
arr = np.random.randn(3,3)
print(arr)
a = arr.sum(1)
print(a)
b = (arr.sum(0))/3
print(b)


[[-1.13372786  0.97683996  0.51264777]
 [ 1.0020858   0.50972513 -0.0974176 ]
 [ 0.22029851  0.79254113  1.28393576]]
[0.35575986 1.41439333 2.29677541]
[0.02955215 0.75970207 0.56638864]


In [33]:
"""3.创建两个 3×2 和 2×3 矩阵，做合法矩阵乘法。"""
import numpy as np
arr1 = np.random.randint(1,9,size=(3,2))
print(arr1)
arr2 = np.random.randint(1,9,size=(2,3))
print(arr2)
a = np.dot(arr1,arr2)
print(a)


[[7 8]
 [3 6]
 [1 1]]
[[7 3 6]
 [4 4 8]]
[[ 81  53 106]
 [ 45  33  66]
 [ 11   7  14]]


In [54]:
"""4.生成 5×5 矩阵，把大于平均值的元素全部设为 0。"""
import numpy as np
arr = np.random.random(25)
b = np.mean(arr)
arr = arr.reshape(5,5)
print(arr)
c = arr > b
print(c)
arr[c] = 0
print(arr)

[[0.73971933 0.87915645 0.15317631 0.07776476 0.1446807 ]
 [0.41620087 0.42700435 0.80314687 0.03026248 0.65887311]
 [0.97570795 0.55934019 0.70919925 0.18250775 0.45396683]
 [0.10979247 0.6112262  0.50369404 0.75961235 0.86428124]
 [0.14502465 0.81083501 0.65948759 0.93928288 0.94778383]]
[[ True  True False False False]
 [False False  True False  True]
 [ True  True  True False False]
 [False  True False  True  True]
 [False  True  True  True  True]]
[[0.         0.         0.15317631 0.07776476 0.1446807 ]
 [0.41620087 0.42700435 0.         0.03026248 0.        ]
 [0.         0.         0.         0.18250775 0.45396683]
 [0.10979247 0.         0.50369404 0.         0.        ]
 [0.14502465 0.         0.         0.         0.        ]]


In [19]:
"""1.晶胞坐标处理：生成简单立方晶胞的原子坐标（比如 8 个顶点：[[0,0,0], [0,0,1], ..., [1,1,1]]），用 NumPy 计算：
 所有原子坐标的平均值；
 任意两个原子之间的距离（用 np.linalg.norm）"""
import numpy as np
arr = np.array([[0,0,0],[0,0,1],[0,1,1],[1,1,1],[1,1,0],[1,0,0],[1,0,1],[0,1,0]])
print(arr)
a = arr.mean(axis=0)
print([a])
c = arr[3]
d = arr[5]
e = c - d
f = np.linalg.norm(e)
print(f)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 0]
 [1 0 1]
 [0 1 0]]
[array([0.5, 0.5, 0.5])]
1.4142135623730951


In [73]:
"""2.模拟数据处理：
生成一组模拟的材料性能数据（100 个样本，5 个特征，用 np.random.rand(100,5)），计算：
每个特征的最大值、最小值、标准差；
筛选出 “第 1 个特征> 0.5 且第 2 个特征 < 0.3” 的样本。"""
#import numpy as np
#arr = np.random.rand(10,5)
#print(arr)
#n = 0
#for n in range(10):
#c = arr[n][0] > 0.5
#d = arr[n][1] < 0.3
#print(arr[n][c][d])

#修改:
import numpy as np
# 1. 生成100个样本、5个特征的模拟材料性能数据
material_data = np.random.rand(100, 5)
print("模拟材料数据（前5行）：\n", material_data[:5])

# 2. 计算每个特征的最大值、最小值、标准差（axis=0 按列计算）
max_vals = material_data.max(axis=0)
min_vals = material_data.min(axis=0)
std_vals = material_data.std(axis=0)

print("\n每个特征的最大值：", max_vals)
print("每个特征的最小值：", min_vals)
print("每个特征的标准差：", std_vals)

# 3. 筛选：第1个特征>0.5 且 第2个特征<0.3（NumPy布尔掩码，不用循环！）
# 注意：Python/NumPy索引从0开始，“第1个特征”是[:,0]，“第2个特征”是[:,1]
mask = (material_data[:, 0] > 0.5) & (material_data[:, 1] < 0.3)
filtered_data = material_data[mask]

print("\n符合条件的样本数：", len(filtered_data))
print("符合条件的样本：\n", filtered_data)


模拟材料数据（前5行）：
 [[0.04728195 0.55549393 0.54598845 0.47966961 0.36600817]
 [0.32776076 0.25043384 0.47505848 0.77731753 0.03661439]
 [0.42760944 0.35407158 0.66016398 0.38292499 0.92284723]
 [0.64721569 0.41689899 0.94492755 0.80146397 0.92906313]
 [0.51706568 0.87272462 0.41105121 0.53659289 0.6203912 ]]

每个特征的最大值： [0.99780354 0.9938244  0.98900416 0.99910351 0.98620333]
每个特征的最小值： [0.00360468 0.00263132 0.02252939 0.00051933 0.01639612]
每个特征的标准差： [0.28798037 0.28662858 0.28415551 0.28586084 0.27953773]

符合条件的样本数： 17
符合条件的样本：
 [[7.62827672e-01 2.50539611e-01 1.63293773e-01 5.69352850e-01
  8.52434371e-01]
 [6.74429497e-01 9.81872975e-02 9.89004156e-01 1.43683781e-01
  4.69575445e-01]
 [5.33387150e-01 2.31656979e-01 6.19052592e-01 5.19331255e-04
  5.04456403e-01]
 [6.46760060e-01 2.29513761e-02 4.48553991e-01 7.30212411e-02
  1.62164127e-01]
 [9.41254643e-01 1.27172563e-01 6.92887202e-01 9.83848593e-01
  1.81727747e-02]
 [8.83221764e-01 2.63131836e-03 1.62569543e-01 7.93536105e-01
  4.220

In [74]:
"""3.晶格常数计算：
给定一个 3×3 的晶格矩阵（比如简单立方：[[a,0,0],[0,a,0],[0,0,a]]），用 np.linalg.det 计算晶胞体积，用 np.linalg.eig 求晶格矩阵的特征值（验证晶格常数）。"""
import numpy as np
a = 3
arr = np.array([[a,0,0],[0,a,0],[0,0,a]])
print(arr)
v = np.linalg.det(arr)
print(v)
r = np.linalg.eig(arr)
print(r)

[[3 0 0]
 [0 3 0]
 [0 0 3]]
27.0
EigResult(eigenvalues=array([3., 3., 3.]), eigenvectors=array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [91]:
"""Add.生成一个形状为 (50, 4) 的随机数组（50 个材料，4 个性能）
计算：
1.每一列的平均值
2.每一列的标准差
3.筛选出同时满足以下条件的所有材料：
  第 0 列 > 0.5
  第 1 列 < 0.5
4.打印筛选出来的数组，以及它的形状"""
import numpy as np
arr = np.random.rand(50,4)
print(arr)
a = arr.mean(axis=0)
print("平均值：",a)
b = arr.std(axis=0)
print("标准差：",b)
c = (arr[:,0] > 0.5) & (arr[:,1] < 0.5)
d = arr[c]
print("目标及目标形状：",d)
print(d.shape)

[[0.50429924 0.94620728 0.92422874 0.75977359]
 [0.16567056 0.62345303 0.90637773 0.17583119]
 [0.47876777 0.19416891 0.11850155 0.01525156]
 [0.00594561 0.1839657  0.07763098 0.79329852]
 [0.95691022 0.80691394 0.52974789 0.40680745]
 [0.27489708 0.79962248 0.74302987 0.13870951]
 [0.87137023 0.62142963 0.4758358  0.39729574]
 [0.42387029 0.96432963 0.67354288 0.63195524]
 [0.30423777 0.40816453 0.17433455 0.72632486]
 [0.69871875 0.98460278 0.55691155 0.60158981]
 [0.64060299 0.21599549 0.93660339 0.13806837]
 [0.0431529  0.40048906 0.30386223 0.54118512]
 [0.56905652 0.92672205 0.28957236 0.41098934]
 [0.82753706 0.02096194 0.25886492 0.93736324]
 [0.24713433 0.02517061 0.83633691 0.9763983 ]
 [0.45754577 0.74342251 0.64736533 0.89094041]
 [0.83110057 0.72032533 0.92385335 0.76028565]
 [0.4492121  0.03109377 0.04099568 0.70077777]
 [0.70324121 0.66904438 0.00517144 0.61033755]
 [0.11513266 0.45765588 0.88072141 0.11202663]
 [0.27621081 0.41346002 0.73551831 0.38718687]
 [0.66863182 