In [3]:
import numpy as np
arr = np.arange(10)
arr.reshape(2,-1)




array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
import numpy as np
arr = np.eye(3,dtype=int)
arr*4.0



array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [24]:
import numpy as np
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
c = a - b
print(c)

[[-3 -3 -3]]


In [26]:
d = np.linalg.norm(c)

In [27]:
d

np.float64(5.196152422706632)

In [29]:
import numpy as np
a = np.array([2,1,5])
b = np.array([4,3,7])
c = a - b
print(np.linalg.norm(c))

3.4641016151377544
