In [11]:
import numpy as np
arr = np.arange(10)
print(arr)
print(arr.shape)
print(arr.reshape(2,-1))
arr1 = np.eye(3)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr2 = arr1 * 4
print(arr2)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a - b
print(c)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
[-3 -3 -3]


In [18]:
A = atom_a = np.array([2,1,5])
B = atom_b = np.array([4,5,6])
ex = A - B
d = np.linalg.norm(ex)
print(d)
C = atom_a = np.array([1,1,1])
D = atom_b = np.array([2,3,4])
ex1 = C - D
d1 = np.linalg.norm(ex1)
print(d1)

4.58257569495584
3.7416573867739413


In [26]:
arr2 = np.arange(9).reshape(3,3)
print(arr2)
arr3 = arr2[0]
print(arr3)
ex2 = C - arr3
d2 = np.linalg.norm(ex2)
print(d2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
1.4142135623730951
