In [9]:
import numpy as np
A = np.array([1.2, 2.3, 3.4])
B = np.array([4.1, 0.8, 2.9])
A0 = 5.0
A[0] = A[0] + A0
A[2] = A[2] - 0.5 * A0
B[1] = B[1] + 2 * A0
ex = A - B
d = np.linalg.norm(ex)
d1 = np.linalg.norm(A)
print(d)
print(d1)

8.981091247727083
6.673829485385434


In [18]:
arr = np.random.random(16).reshape(4,4)
print(arr)
y = arr[1,2]
print(y)
arr[:,3] = arr[:,3] * 3.8
print(arr)
a1 = arr[0]
a2 = arr[2]
exa1_2 = a1 - a2
print(np.linalg.norm(exa1_2))
arr_t = arr.T
print(arr_t)

[[0.2668432  0.16025766 0.6905398  0.79374379]
 [0.67798014 0.30837941 0.24614404 0.9892081 ]
 [0.53097913 0.49067924 0.09815483 0.83319343]
 [0.60162898 0.3039305  0.68077562 0.04865732]]
0.2461440389674302
[[0.2668432  0.16025766 0.6905398  3.0162264 ]
 [0.67798014 0.30837941 0.24614404 3.7589908 ]
 [0.53097913 0.49067924 0.09815483 3.16613503]
 [0.60162898 0.3039305  0.68077562 0.1848978 ]]
0.7431949667584816
[[0.2668432  0.67798014 0.53097913 0.60162898]
 [0.16025766 0.30837941 0.49067924 0.3039305 ]
 [0.6905398  0.24614404 0.09815483 0.68077562]
 [3.0162264  3.7589908  3.16613503 0.1848978 ]]


In [38]:
atoms = np.array([[1,2,3], [4,5,6], [7,8,9], [2,4,6], [5,7,9]])
o = atoms[0]
list1 = []
print(o)
for x in atoms[1:]:
    d = np.linalg.norm(o - x)
    list1.append(d)
    print(d)
print("最远：",max(list1),"位置；",list1.index(max(list1)) + 1)

m = np.mean(atoms,axis = 0) ##加强记忆
for y in atoms:
    d1 = np.linalg.norm(m - y)
    print(d1)




[1 2 3]
5.196152422706632
10.392304845413264
3.7416573867739413
8.774964387392123
最远： 10.392304845413264 位置； 2
5.571355310873647
0.6633249580710797
4.882622246293481
2.2449944320643644
3.2310988842807027
